### ISSUE TITLE
pushy-node throws an exception when the response body from Pushy API is undefined

### ISSUE THREAD

**Issue by dylanswartz** [pushy-me/pushy-node#1]
I receive the following error in my application (which causes my application to crash) when a response from Pushy API does not include a body. 

/node_modules/pushy-node/index.js:94
            if (body.error) {
                    ^
TypeError: Cannot read property 'error' of undefined
    at Request._callback (/opt/tracker-service/releases/188/node_modules/pushy-node/index.js:94:21)
    at Request.self.callback (/opt/tracker-service/releases/188/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/opt/tracker-service/releases/188/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/opt/tracker-service/releases/188/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by pushy** [comment]
Thanks @dylanswartz, this has been fixed in https://github.com/pushy-me/pushy-node/commit/b3bcbedf065dedff2823d6b30d036e860987c577 and published in `2.0.4`. 👍
